# Generated by Django 3.2 on 2021-05-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courtmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=45)),
                ('First_Name', models.CharField(max_length=45)),
                ('Last_Name', models.CharField(max_length=45)),
                ('CaseType', models.CharField(max_length=45)),
                ('Address', models.CharField(max_length=45)),
                ('phone_no', models.CharField(max_length=45)),
                ('Status', models.CharField(max_length=45)),
                ('Age', models.CharField(max_length=45)),
                ('Judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtmanagement.judge')),
                ('LowOfficer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtmanagement.lowofficer')),
            ],
        ),
    ]
