# Generated by Django 3.2 on 2021-05-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courtmanagement', '0002_casestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignjudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profileimage.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profileimage.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Casestore',
        ),
        migrations.AddField(
            model_name='assignjudge',
            name='Case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtmanagement.case'),
        ),
        migrations.AddField(
            model_name='assignjudge',
            name='Judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtmanagement.judge'),
        ),
        migrations.AddField(
            model_name='assignjudge',
            name='LowOfficer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtmanagement.lowofficer'),
        ),
    ]
