# Generated by Django 3.2 on 2021-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtmanagement', '0009_remove_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Case_Id',
            field=models.CharField(default=123, max_length=45),
            preserve_default=False,
        ),
    ]
