# Generated by Django 3.2 on 2021-06-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtmanagement', '0010_case_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='caseqr_codes'),
        ),
    ]
