# Generated by Django 3.2 on 2021-06-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtmanagement', '0013_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='plainttif profileimage/'),
        ),
    ]
